### ISSUE TITLE
Update watson-developer-cloud

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-runtime-nodejs#10]
@cfjedimaster commented on [Fri Jan 06 2017](https://github.com/apache/incubator-openwhisk/issues/1699)

OpenWhisk is using a 1.* version of the watson-developer-cloud package, which is now at 2.*. Please see if you can upgrade to that version.

**Comment by csantanapr** [comment]
closed as going forward no vendor libraries should be added to the base.
The vendor and operators can extend this image an offer a nodejs kind with included vendor libraries like IBM Functions do today for nodejs:8 kind it includes watson, cloudant, and other sdks
