### ISSUE TITLE
expand support for specifying --main to override package.json

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-runtime-nodejs#131]
Currently the action running for zip files requires either an `index.js` or `package.json` with a `main` entry module declared. I propose expanding the support for specifying "main" (e.g., `wsk action create --main module.function`) so that one can override the  module to be loaded too.

**Comment by jthomas** [comment]
This is a good addition to the runtime!

**Comment by tysonnorris** [comment]
Sounds good. Just wondering - are there any runtimes where `.` might pose a problem as a separator?

**Comment by rabbah** [comment]
I don't know but I'm only thinking of node.js. I think the way you specify "main" has to be language specific and this value is opaque to the openwhisk control plane.

**Comment by tysonnorris** [comment]
Ok, so no validation at CLI or API? That's fine then.

**Comment by rabbah** [comment]
I wasn't intending to broaden the scope - I think the CLI would be the right place for it in the future.

**Comment by csantanapr** [comment]
Your thinking is for example:
having a zip file with a file foo.js
Inside foo.js have a function bar exported
export = {
bar: function(){....}
...}

Then the epilogue will run
require($pathtoexpandedzip/foo.js).bar(args)

**Comment by csantanapr** [comment]
You realize your making easier to create a gigantic monolith deployment zip with all your functions deployed at once. 

I guess not bad if they use it properly for their common/utils functions that don’t change much and used as a lib.
