### ISSUE TITLE
Change in global scope eval causes `main` to not be found in bundled action (typescript + webpack)

### ISSUE THREAD

**Issue by rasantiago** [apache/incubator-openwhisk-runtime-nodejs#138]
Using local deployment of OW through docker compose on mac.  All has been wonderful till a couple days ago when I did a fresh install and my actions started returning:

```
"error": "Initialization has failed due to: Action entrypoint 'main' is not a function."
```

My actions are built using typescript and webpack based on the pattern found in [IBM Cloud Function Typescript Starter Kit](https://github.com/IBM-Cloud/openwhisk-typescript).

It looks like this [change to the global scope eval](https://github.com/apache/incubator-openwhisk-runtime-nodejs/commit/afc93ba231de2970df4fd7228cb5c04327addc10) is responsible.

Here is a small bundled action that should reproduce  the issue:
```
!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=407)}({407:function(e,t,n){"use strict";var r=this&&this.__awaiter||function(e,t,n,r){return new(n||(n=Promise))(function(o,u){function i(e){try{f(r.next(e))}catch(e){u(e)}}function c(e){try{f(r.throw(e))}catch(e){u(e)}}function f(e){e.done?o(e.value):new n(function(t){t(e.value)}).then(i,c)}f((r=r.apply(e,t||[])).next())})};function o(){return r(this,void 0,void 0,function*(){return{statusCode:200,body:{status:"ok"}}})}Object.defineProperty(t,"__esModule",{value:!0}),t.default=o,global.main=o}});
```

**Comment by rasantiago** [comment]
Just to add some more confirmation of the bug:

If I take the bundled function above along with the latest image (`afc93ba`) and test with:

```
wsk action update test test.js --docker openwhisk/action-nodejs-v10:afc93ba
wsk action invoke test
```

I get `"error": "Initialization has failed due to: Action entrypoint 'main' is not a function."`

But if I use the commit right prior (`8f705d1`):

```
wsk action update test test.js --docker openwhisk/action-nodejs-v10:8f705d1
wsk action invoke test
```
I get `"status": "ok"`

Also just helped a colleague through this error.  This might be a serious bug.

**Comment by rasantiago** [comment]
@rabbah and @mrutkows Any chance you could take a look?

**Comment by rabbah** [comment]
Thanks for the details posted already. I’ll have a look.

**Comment by rabbah** [comment]
Here's a workaround:

```
> ~/projects/openwhisk/tools/actionProxy/invoke.py init global.main t.js 
{"OK":true}
> ~/projects/openwhisk/tools/actionProxy/invoke.py run
{"statusCode":200,"body":{"status":"ok"}}
```

Set `--main global.main`.

**Comment by rabbah** [comment]
@rasantiago I have reverted some of the changes that lead to this breakage here https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/141. I added the function you provided as a test case but would like to replace it with something simpler (also I don't know the provenance of your code in the test case). If you'd like to contribute a simpler test case please feel free to send a PR either to my fork or to this repo and I'll assimilate the changes.
