### ISSUE TITLE
Seems that nodejs:10 doesnt have package redis

### ISSUE THREAD

**Issue by lesomnus** [apache/incubator-openwhisk-runtime-nodejs#144]
## Environment details:

* local deployment, docker compose in dev-tools

## Steps to reproduce the issue:

1.   compose workflow
2.   deploy with default option (kind = nodejs:10)
3.   invoke

## Provide the expected results and outputs:

start workflow

## Provide the actual results and outputs:

{    "error": "Initialization has failed due to: Error: Cannot find module 'redis'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at eval (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:361:55)\n    at eval (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:446:3)\n    at eval (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:447:14)\n    at initializeActionHandler (/nodejsAction/runner.js:57:23)\n    at doInit (/nodejsAction/src/service.js:163:16)\n    at initCode (/nodejsAction/src/service.js:93:24)"
}

## Additional information you deem important:
the workflow starts when deploying it with --kind=nodejs:6

**Comment by lesomnus** [comment]
I have seen package.json have no dependency on redis but nodejs: 6.
If so, the composer should only run on nodejs: 6. Why does the deploy command default to nodejs: 10?
Is openwhisk installed on my machine registering nodejs: 10 as runtime by default?

**Comment by style95** [comment]
@lesomnus Hi.
Thank you for the report.


There was a discussion about this: https://lists.apache.org/thread.html/6247da5513692d4a0b55ffe5de1b6cd8fc74168ae4ab1934264aebd9@%3Cdev.openwhisk.apache.org%3E

And we decided to keep the upstream runtime as pure as possible based on the assumption that 
 required packages can be added by OW operator in each downstream.
It would be easier for downstream to customize packages if we keep the upstream pure enough.


Regarding the default runtime, we relatively recently updated our default runtime to nodejs:10, so there might be some missing parts which do not take in `nodejs:10` as a defaut runtime yet.
We are still updating them whenever we find them.

Thank you to let us know.

**Comment by lesomnus** [comment]
thank you for the reply.

**Comment by rabbah** [comment]
Including Redis (since it’s useful for composer) might be a good idea. @tardieu?
