### ISSUE TITLE
Some source files miss Apache license headers

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-runtime-nodejs#25]
Following [Apache license header guideline](http://www.apache.org/legal/src-headers.html), **all human-readable Apache-developed files that are included within a distribution must include the header text with few exceptions**. You can find few exceptions here: [which files do not require a license header](http://www.apache.org/legal/src-headers.html#faq-exceptions).

I used Apache Rat to check this repository after excluding a few files, and I got this report. We need to add Apache licensing header to those files.
```
Unapproved licenses:

  openwhisk-runtime-nodejs/core/nodejsActionBase/Dockerfile
  openwhisk-runtime-nodejs/core/nodejs6Action/CHANGELOG.md
  openwhisk-runtime-nodejs/core/nodejs6Action/Dockerfile
  openwhisk-runtime-nodejs/core/nodejs8Action/CHANGELOG.md
  openwhisk-runtime-nodejs/core/nodejs8Action/Dockerfile
  openwhisk-runtime-nodejs/tests/src/test/resources/application.conf
  openwhisk-runtime-nodejs/ansible/environments/local/group_vars/all
  openwhisk-runtime-nodejs/ansible/environments/local/hosts
```

The excluded files are:
```
**/*.json
**/**.gradle
**/gradlew
**/gradle/**
**/.**
**/templates/**
**/*.j2.*
**/.github/**
**/auth.whisk.system
**/auth.guest
**/i18n_resources.go
```

**Comment by daisy-ycguo** [comment]
I suggest to exclude below files from header scanning because they are config files with few creativity.

```
  openwhisk-runtime-nodejs/tests/src/test/resources/application.conf
  openwhisk-runtime-nodejs/ansible/environments/local/group_vars/all
  openwhisk-runtime-nodejs/ansible/environments/local/hosts
```

**Comment by mrutkows** [comment]
@daisy-ycguo Since PR[38](https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/38) was merged (55 files had the ASF license added), are there any files remaining that are missing ASF license headers?  Are there any exclusions we need to list in our on-line documentation?

**Comment by daisy-ycguo** [comment]
Since we changed the policy to settings.gradle and build.gradle (see the discussion [here](https://github.com/apache/incubator-openwhisk-release/issues/131), we need this PR merged. And then we can close this issue.

**Comment by daisy-ycguo** [comment]
We can close it. All files documented [here](https://github.com/apache/incubator-openwhisk-release/blob/master/docs/license_compliance.md) are with ASF headers.
