### ISSUE TITLE
Add nodejs:10 LTS

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-nodejs#43]
It would be good to start building the image for nodejs:10 even if its to get the image posted to be use by folks and get feedback.
Would not recommend to add to core repo default deployment until LTS in Oct 2018.

**Comment by csantanapr** [comment]
First build is out today 🎉
https://nodejs.org/dist/v10.0.0/

**Comment by jthomas** [comment]
Node.js 10 is now released 💯. Time to start thinking about including it....
